[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "qwenimage"
version = "0.1"

[tool.setuptools.packages.find]
where = ["."]
include = ["qwenimage*"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements/requirements.txt"]}