wandb_run_name: "reg-base"
output_dir: "/data/checkpoints/reg-base"

learning_rate: 1e-4
num_train_epochs: 1
max_train_steps: null
preprocessing_epoch_len: 0
preprocessing_epoch_repetitions: 1
num_validation_images: &val_num 32
num_sample_images: 4
train_range: [*val_num, null]
val_range: [0, *val_num]
test_range: [0, 4]
regression_base_pipe_steps: 4

training_type: "regression"

regression_data_dir: "/data/regression_output"
regression_gen_steps: 50
editing_data_dir: "/data/CrispEdit"
editing_total_per: 1
